### ISSUE TITLE
Benchmarks hang

### ISSUE THREAD

**Issue by insanitybit** [aDotInTheVoid/meta-regex-golf#1]
Hi, I cloned the repo and attempted to benchmark. It hangs at process.py

```
=== python3 norvig_nocache.py ===
real 1.049000
user 1.040000
sys 0.002000

=== python3 norvig_with_cache.py ===
real 0.679000
user 0.674000
sys 0.000000

=== python3 process.py ===
^[.^[.^CTraceback (most recent call last):
  File "process.py", line 7, in <module>
    x = x + input() + "\n"
KeyboardInterrupt
^CTraceback (most recent call last):
  File "process.py", line 7, in <module>
    x = x + input() + "\n"
KeyboardInterrupt
```

**Comment by aDotInTheVoid** [comment]
`bench.sh` expects all python scripts to be benchable.  For now, the workaround is to remove `process.py` or modify `bench.sh` to not run on all python scripts.

Eventualy I thing I'm going to switch to [hyperfine](https://github.com/sharkdp/hyperfine) to replace `process.py` and `bench.sh`

**Comment by insanitybit** [comment]
Cool, I removed process.py and that solved it, but I wasn't sure if that was intended behavior. Thanks for putting this up, I enjoyed the article enough to pull down the code and play around a bit.
